#define a {
#define b }
#define c ;
#define d ,
#define e =
#define f !
#define g .
#define h (
#define i )
#define j [
#define k ]
#define l +
#define m -
#define n *
#define o /
#define p %
#define q <
#define r >
#define s &
#define t |
#define u ^
#define v ~
#define w ?
#define x :
#define y if
#define z else
#define A while
#define B do
#define C for
#define D switch
#define E case
#define F break
#define G continue
#define H return
#define I default
#define J sizeof
#define K typedef
#define L struct
#define M union
#define N enum
#define O static
#define P extern
#define Q void
#define R char
#define S short
#define T int
#define U long
#define V float
#define W double
#define X signed
#define Y unsigned
#define Z const
#define aa volatile
#define bb auto
#define cc register
#define dd goto
#define ee #define
#define ff #include
#define gg #undef
#define hh #if
#define ii #ifdef
#define jj #ifndef
#define kk #else
#define ll #elif
#define mm #endif
#define nn #error
#define oo #pragma
#define pp #line
#define qq #include_next
#define rr #warning
#define ss #undefine
#define tt #ifnot
#define uu #elifnot
#define ww '
#define xx true
#define yy false
#define zz NULL
#define AA \



